import type { Metadata } from "next";
import "./globals.css";
import ToasterProvider from "./component/toasterprovider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <ToasterProvider /> {/* ✅ Ajout du Toaster ici */}
        {children}
      </body>
    </html>
  );
}
